# Generated by Django 3.2.9 on 2021-12-08 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Attendence',
            new_name='Attendance',
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='attendence',
            new_name='attendance',
        ),
    ]
